export default {
  list:[
    {
      typeName:'listItemWithTitle',
      title:'',
      description:''
    },
    {
      typeName:'InfoItem',
      content:''
    },
    {
      typeName:'ListItemWithoutTitle',
      content:''
    },
    {
      typeName:'svgBarItem',
      title:'',
      width:100
    }
  ]
};