export default {
  list:[
    {
      typeName:'listItemWithTitle',
      title:'',
      description:''
    },
    {
      typeName:'imgItem',
      src:'',
      description:''
    },
    {
      typeName:'listItem',
      content:''
    },
    {
      typeName:'svgBarItem',
      title:'',
      width:100
    }
  ]
};